### ISSUE TITLE
Fix and feature enable Bug-Report-Button-on-every-screen

### ISSUE THREAD

**Issue by proSingularity** [proSingularity/you-are-awesome-app#473]
When setting the feature-toggle for the bug-report-button on every screen, the CI failed last time. Fix it and enable the feature.

## ACs

- [x] feature is enabled
- [x] CI works
- [x] tests for bug-report-button are enabled

## DoD

- [x] merged into `master`
- [x] emulator app on `master` still starts
- [x] emulator app on `master` contains the update
- [x] `yarn deploy:prod` succeeded
- [x] production app on my phone still starts
- [x] production app on my phone contains the update
- [x] production app on my phone tests the changed functionality ad-hoc
- [x] merged update to build version to `master`

**Comment by proSingularity** [comment]
likely to be the culprit 

https://github.com/proSingularity/you-are-awesome-app/runs/2896689892

```log
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `PortalManager`.
        in PortalManager (created by Portal.Host)
        in Portal.Host (created by Provider)
        in Provider (created by MockPaperProvider)
        in MockPaperProvider (created by LocalizedMockPaperProvider)
        in LocalizedMockPaperProvider".

      at console.error (node_modules/@jest/console/build/BufferedConsole.js:165:10)
      at printWarning (node_modules/react/cjs/react.development.js:315:30)
      at error (node_modules/react/cjs/react.development.js:287:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1788:7)
      at node_modules/react-native-paper/lib/commonjs/components/Portal/PortalManager.js:171:22
          at Array.map (<anonymous>)
      at PortalManager.render (node_modules/react-native-paper/lib/commonjs/components/Portal/PortalManager.js:168:33)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7618:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7568:24)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9043:16)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "The above error occurred in the <PortalManager> component:
        in PortalManager (created by Portal.Host)
        in Portal.Host (created by Provider)
        in Provider (created by MockPaperProvider)
        in MockPaperProvider (created by LocalizedMockPaperProvider)
        in LocalizedMockPaperProvider
```
